### ISSUE TITLE
iohub verbose fails if hcs plate has only one position

### ISSUE THREAD

**Issue by edyoshikun** [czbiohub-sf/iohub#206]
If one creates an HCS plate with one well and one position, the `iohub info -v ` fails. This only happens with the `verbose -v` flag as this calls reader.positions(). 

This dataset has only one well and one FOV (fails):
`iohub info -v /hpc/projects/comp.micro/mantis/2023_11_01_OpenCell_infection/5.2-VS_test_pred/pcna_timelapse_230809_reg1e-3.zarr/0/0/0`

This datset has 3 wells and one FOV per well (works):
`iohub info -v /hpc/projects/comp.micro/mantis/2023_11_01_OpenCell_infection/5.2-VS_test_pred/pcna_timelapse_230809_v2.zarr/0/0/0`

```bash
iohub info -v /hpc/projects/comp.micro/mantis/2023_08_09_HEK_PCNA_H2B/10-debug_vs/data/reg_1e-3/timelapse_reg_1e-3.zarr/0/0/0
Reading file:    /hpc/projects/comp.micro/mantis/2023_08_09_HEK_PCNA_H2B/10-debug_vs/data/reg_1e-3/timelapse_reg_1e-3.zarr/0/0/0
Traceback (most recent call last):
  File "/hpc/mydata/eduardo.hirata/.conda/envs/viscy/bin/iohub", line 8, in <module>
    sys.exit(cli())
  File "/hpc/mydata/eduardo.hirata/.conda/envs/viscy/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/hpc/mydata/eduardo.hirata/.conda/envs/viscy/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/hpc/mydata/eduardo.hirata/.conda/envs/viscy/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/hpc/mydata/eduardo.hirata/.conda/envs/viscy/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/hpc/mydata/eduardo.hirata/.conda/envs/viscy/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/hpc/mydata/eduardo.hirata/.conda/envs/viscy/lib/python3.10/site-packages/iohub/cli/cli.py", line 43, in info
    print_info(file, verbose=verbose)
  File "/hpc/mydata/eduardo.hirata/.conda/envs/viscy/lib/python3.10/site-packages/iohub/reader.py", line 310, in print_info
    f"Positions:\t {len(list(reader.positions()))}",
AttributeError: 'Position' object has no attribute 'positions'
```

**Comment by edyoshikun** [comment]
I was able to reproduce this using `iohub, version 0.1.0.dev4`.

**Comment by ziw-liu** [comment]
Done in https://github.com/mehta-lab/VisCy/pull/64
